"_______________________________________________________________________
" This file is included with the Vim color scheme generated by
" Color Scheme Exporter
"_______________________________________________________________________

"_______________________________________________________________________
" COLOR SCHEME DEFINITION
"_______________________________________________________________________
set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = 'flux-bunny-dark'

"_______________________________________________________________________
" COLOR DEFINITONS
"_______________________________________________________________________

"-----------------------------------------------------------------------
" GUI Colors
"-----------------------------------------------------------------------

let gui_bg__norm = '#262626'
let gui_fg__norm = '#c6c6c6'

let gui_blk_norm = '#1c1c1c'
let gui_red_norm = '#d787af'
let gui_grn_norm = '#afd787'
let gui_yel_norm = '#ffd787'
let gui_blu_norm = '#87afd7'
let gui_mag_norm = '#af87d7'
let gui_cya_norm = '#87d7af'
let gui_wht_norm = '#d7d7d7'

let gui_bg__bold = '#303030'
let gui_fg__bold = '#eeeeee'

let gui_blk_bold = '#5f5f5f'
let gui_red_bold = '#ff5f87'
let gui_grn_bold = '#5faf87'
let gui_yel_bold = '#ff875f'
let gui_blu_bold = '#00afd7'
let gui_mag_bold = '#af5faf'
let gui_cya_bold = '#5fafaf'
let gui_wht_bold = '#eeeeee'

"-----------------------------------------------------------------------
" CLI Colors
"-----------------------------------------------------------------------
let cli_bg__norm = '235'
let cli_fg__norm = '251'

let cli_blk_norm = '234'
let cli_red_norm = '175'
let cli_grn_norm = '150'
let cli_yel_norm = '222'
let cli_blu_norm = '110'
let cli_mag_norm = '140'
let cli_cya_norm = '115'
let cli_wht_norm = '188'

let cli_bg__bold = '236'
let cli_fg__bold = '255'

let cli_blk_bold = '59'
let cli_red_bold = '204'
let cli_grn_bold = '72'
let cli_yel_bold = '209'
let cli_blu_bold = '38'
let cli_mag_bold = '133'
let cli_cya_bold = '73'
let cli_wht_bold = '255'

" File containing the highlight group configurations
source ~/.vim/colors/flux-bunny-base.vim