"_______________________________________________________________________
" This file is included with the Vim color scheme generated by
" Color Scheme Exporter
"_______________________________________________________________________

"_______________________________________________________________________
" COLOR SCHEME DEFINITION
"_______________________________________________________________________
set background=light
hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = 'flux-bunny-lite'

"_______________________________________________________________________
" COLOR DEFINITONS
"_______________________________________________________________________

"-----------------------------------------------------------------------
" GUI Colors
"-----------------------------------------------------------------------

let gui_bg__norm = '#e4e4e4'
let gui_fg__norm = '#262626'

let gui_blk_norm = '#121212'
let gui_red_norm = '#af005f'
let gui_grn_norm = '#008700'
let gui_yel_norm = '#d75f00'
let gui_blu_norm = '#005f87'
let gui_mag_norm = '#872f87'
let gui_cya_norm = '#5f8787'
let gui_wht_norm = '#878787'

let gui_bg__bold = '#dadada'
let gui_fg__bold = '#303030'

let gui_blk_bold = '#878787'
let gui_red_bold = '#d75f87'
let gui_grn_bold = '#008700'
let gui_yel_bold = '#d78700'
let gui_blu_bold = '#0087af'
let gui_mag_bold = '#875f87'
let gui_cya_bold = '#005f5f'
let gui_wht_bold = '#afafaf'

"-----------------------------------------------------------------------
" CLI Colors
"-----------------------------------------------------------------------
let cli_bg__norm = '254'
let cli_fg__norm = '235'

let cli_blk_norm = '233'
let cli_red_norm = '125'
let cli_grn_norm = '28'
let cli_yel_norm = '166'
let cli_blu_norm = '24'
let cli_mag_norm = '90'
let cli_cya_norm = '66'
let cli_wht_norm = '102'

let cli_bg__bold = '253'
let cli_fg__bold = '236'

let cli_blk_bold = '102'
let cli_red_bold = '168'
let cli_grn_bold = '28'
let cli_yel_bold = '172'
let cli_blu_bold = '31'
let cli_mag_bold = '96'
let cli_cya_bold = '23'
let cli_wht_bold = '145'

" File containing the highlight group configurations
source ~/.vim/colors/flux-bunny-base.vim